# 2장

In [1]:
import numpy as np

np.<TAB>
np?

In [4]:
np?

In [7]:
L=list(range(10))

In [8]:
L2=[str(c) for c in L]

In [9]:
L3=[True,"2",3.0,4]

In [11]:
import array
L=list(range(10))
A=array.array('i',L)
A?

making numpy array

In [12]:
np.array([1,4,2,5,3]) # numpy array have to include all of same type elements

array([1, 4, 2, 5, 3])

In [18]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
np.zeros(10,dtype=int)
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [20]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.random.random((3,3))

array([[0.72711733, 0.74035163, 0.20612365],
       [0.407102  , 0.20721832, 0.98157316],
       [0.28610115, 0.44362589, 0.72500884]])

In [26]:
np.random.normal(0,1,(3,3)) # mean =0 , val =1

array([[-0.03648415, -0.88385925,  0.56334128],
       [ 0.99792678,  0.18536286, -0.44191212],
       [ 0.03119994, -1.96363878, -0.0726788 ]])

In [27]:
np.random.randint(0,10,(3,3))

array([[1, 3, 4],
       [4, 0, 3],
       [6, 1, 0]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.empty(3)

array([1., 1., 1.])

In [31]:
np.random.seed(0)#from now ramdom function makes same random vlaues

In [33]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))# each arrays include feature(ndim,shape,size)

In [34]:
print("x3 ndim:",x3.ndim) #number of dimension
print("x3 shape:",x3.shape) #size of dimension
print("x3 size:",x3.size) # size of all of dimension

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [35]:
print("dtype:",x3.dtype)

dtype: int32


In [36]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


slicing
x[start:stop:step]

In [39]:
x=np.array(range(10))
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
x[5::-2]

array([5, 3, 1])

In [44]:
x2 = np.array([[12,5,2,4],
          [7,6,8,8],
          [1,6,7,7]]) # when use np.array() in () can accept only 1 array  

In [47]:
x2[:2,:3]# 2rows,3columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [48]:
x2[:3,:2]# 3rows,2columns

array([[12,  5],
       [ 7,  6],
       [ 1,  6]])