# 2장

In [1]:
import numpy as np

np.<TAB>
np?

In [2]:
np?

In [3]:
L=list(range(10))

In [4]:
L2=[str(c) for c in L]

In [5]:
L3=[True,"2",3.0,4]

In [6]:
import array
L=list(range(10))
A=array.array('i',L)
A?

making numpy array

In [7]:
np.array([1,4,2,5,3]) # numpy array have to include all of same type elements

array([1, 4, 2, 5, 3])

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.zeros(10,dtype=int)
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [10]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.11425823, 0.40040139, 0.1766398 ],
       [0.29482372, 0.92184313, 0.00137719],
       [0.97351542, 0.42803423, 0.3571434 ]])

In [15]:
np.random.normal(0,1,(3,3)) # mean =0 , val =1

array([[-0.59920525,  0.73875155,  0.91791065],
       [-0.05206974,  1.37116208, -0.50797769],
       [-0.88565662,  0.52051553, -0.54594816]])

In [16]:
np.random.randint(0,10,(3,3))

array([[4, 5, 5],
       [8, 1, 6],
       [3, 1, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

In [19]:
np.random.seed(0)#from now ramdom function makes same random vlaues

In [20]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))# each arrays include feature(ndim,shape,size)

In [21]:
print("x3 ndim:",x3.ndim) #number of dimension
print("x3 shape:",x3.shape) #size of dimension
print("x3 size:",x3.size) # size of all of dimension

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [22]:
print("dtype:",x3.dtype)

dtype: int32


In [23]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


slicing
x[start:stop:step]

In [24]:
x=np.array(range(10))
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
x[5::-2]

array([5, 3, 1])

In [26]:
x2 = np.array([[12,5,2,4],
          [7,6,8,8],
          [1,6,7,7]]) # when use np.array() in () can accept only 1 array  

In [27]:
x2[:2,:3]# 2rows,3columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [28]:
x2[:3,:2]# 3rows,2columns

array([[12,  5],
       [ 7,  6],
       [ 1,  6]])

In [29]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [30]:
print(x2[:,0])#first column

[12  7  1]


In [31]:
print(x2[0,:])#first rows
print(x2[0])

[12  5  2  4]
[12  5  2  4]


slice returning view of array!
not copy!

In [32]:
x2_sub=x2[:2,:2]

In [33]:
x2_sub
x2_sub[0,0]=99

In [34]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x2_sub_copy=x2.copy() #method copy() makes copy of array, not view

In [36]:
x2_sub_copy[0,0]=0

In [37]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
grid = np.array(range(9)).reshape((3,3))
print(grid)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
grid =np.arange(0,9).reshape((3,3))
print(grid)
np.arange?

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
x=np.array([1,2,3])

In [41]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [42]:
x.reshape((1,3))

array([[1, 2, 3]])

In [43]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [44]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [45]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [54]:
grid=np.array([[1,2,3],
             [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
             [6,5,4]])
np.vstack((x,grid))#vertical

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [73]:
x=np.array([[99],[99]])
np.hstack((x,grid))#horizontal

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [78]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [87]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
upper,lower=np.vsplit(grid,[2])# [] needs, vertical split
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [113]:
left,right=np.hsplit(grid,[1])# [] needs, horizontal split
print(left)
print(right)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


ufuncs

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
        return output   

In [5]:
big_array=np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array) # calculate the time used to operate function

119 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%timeit(1.0/big_array)

4.75 ms ± 145 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
